Fix for potential issue with context broker policies
orchestracities/anubis pull request #199
Opened 2023-01-18 10:28 UTC by Cerfoglg

## Proposed changes

Checking for post requests to avoid issue with retrieving data

## Types of changes

What types of changes does your code introduce to the project: _Put
an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing
      functionality to not work as expected)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after
creating the PR. If you're unsure about any of them, don't hesitate to
ask. We're here to help! This is simply a reminder of what we are going
to look for before merging your code._

- [x] I have read the [CONTRIBUTING][contrib] doc
- [x] I have signed the [Contributor License Agreement][cla]
- [x] I have updated the [RELEASE NOTES][release]
- [x] I have added tests that prove my fix is effective or that my
      feature works
- [x] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in
      downstream modules

## Further comments

If this is a relatively large or complex change, kick off the discussion
by explaining why you chose the solution you did and what alternatives
you considered, etc...

[cla]: https://raw.githubusercontent.com/orchestracities/anubis/master/individual_cla.pdf
    "Martel Open Source Software Individual Contributor License Agreement"
[contrib]: https://github.com/orchestracities/anubis/blob/master/CONTRIBUTING.md
    "Contributing to Anubis"
[release]: https://github.com/orchestracities/anubis/blob/master/RELEASE_NOTES.md
    "Anubis Release Notes"

2023-01-18 14:23 UTC, chicco785 requested changes

2023-01-18 14:23 UTC, chicco785 commented on config/opa-service/lua/common.lua
>    request_handle:streamInfo():dynamicMetadata():set("envoy.filters.http.lua", "request.info", {
what happens when request.info is not set? would be better to add at least a check on "meta!=null"

2023-01-20 15:42 UTC, Cerfoglg commented
This is not a fix for the issue of the token potentially getting dropped as reported by one user, but I was unable to recreate said issue on my side, and I can't locate an exact reason with the code or current setup, so unless we get more information or further test, we can't pinpoint that particular issue. This pull will fix the nil errors of LUA

2023-01-31 10:32 UTC, c0c0n3 approved these changes

2023-02-01 08:36 UTC, c0c0n3 commented
I have read the CLA Document and I hereby sign the CLA

2023-02-01 08:38 UTC, merged