Update realm-export.json
orchestracities/anubis pull request #46
Opened 2022-03-14 14:52 UTC by Valecant

new realm config

## Proposed changes

Describe the big picture of your changes here to communicate to the
maintainers why we should accept this pull request.
If it fixes a bug or resolves a feature request, be sure to link to
that issue.

## Types of changes

What types of changes does your code introduce to the project: _Put
an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing
      functionality to not work as expected)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after
creating the PR. If you're unsure about any of them, don't hesitate to
ask. We're here to help! This is simply a reminder of what we are going
to look for before merging your code._

- [ ] I have read the [CONTRIBUTING][contrib] doc
- [ ] I have signed the [Contributor License Agreement][cla]
- [ ] I have updated the [RELEASE NOTES][release]
- [ ] I have added tests that prove my fix is effective or that my
      feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in
      downstream modules

## Further comments

If this is a relatively large or complex change, kick off the discussion
by explaining why you chose the solution you did and what alternatives
you considered, etc...

[cla]: https://raw.githubusercontent.com/orchestracities/anubis/master/individual_cla.pdf
    "Martel Open Source Software Individual Contributor License Agreement"
[contrib]: https://github.com/orchestracities/anubis/blob/master/CONTRIBUTING.md
    "Contributing to Anubis"
[release]: https://github.com/orchestracities/anubis/blob/master/RELEASE_NOTES.md
    "Anubis Release Notes"

2022-03-18 09:28 UTC, chicco785 commented
@Valecant as by error checks and tue discussion, can you:
- sign the PR https://github.com/orchestracities/anubis/pull/46#issuecomment-1066898087
- update the RELEASE_NOTES.md

2022-03-18 20:45 UTC, Valecant commented
I have read the CLA Document and I hereby sign the CLA

2022-03-18 20:55 UTC, Valecant commented
I have read the CLA Document and I hereby sign the CLA

2022-03-19 11:01 UTC, chicco785 commented
@Valecant 

1) there was a pr open with the cors support, don't pollute PRs
2) after you update the PR, check it passes, if not fix what's wrong.

2022-03-19 11:03 UTC, chicco785 commented on RELEASE_NOTES.md
> +### Change the main py in order to work with the frontend app
follow the existing structure, don't mess up.
1 - cors is not in this pr, so you can remove it.
2 - simply add the change description to real-export (what was changed), under new features in this case for 0.0.3

2022-03-19 11:04 UTC, chicco785 requested changes

2022-03-19 11:04 UTC, chicco785 commented on anubis-management-api/src/main.py
> +from fastapi.middleware.cors import CORSMiddleware
as said above, following gabriele's pr, code in the master has already cors support.
so remove.

2022-03-25 05:54 UTC, chicco785 requested changes
1. use 0.0.3, add rows there, not a new version
2. remove `.DS_STORE` files

2022-03-25 05:54 UTC, chicco785 commented on RELEASE_NOTES.md
> +## 0.0.4
non creare una nuova versione, fin tanto che non facciamo una release, rimane 0.0.3

2022-03-25 12:59 UTC, chicco785 approved these changes

2022-03-25 13:00 UTC, merged